export default {
  data: [
    {
      Nombre: 'Cancer de Garganta',
      'Piel Roja': 0,
      'Dolor al Orinar': 0,
      Tos: 1,
      Acidez: 0,
      Cansancio: 0.4,
      'Fiebre ': 0.1,
      'Cambio de Peso': 0.8,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0.2,
      'Infección Recurrente': 0.1,
      'Dificultad para Tragar': 0.8,
      'Protuerancia en el cuello': 1,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0, 1, 0, 0.4, 0.1, 0.8, 0, 0, 0.2, 0.1, 0.8, 1, 0, 0, 0, 0]
    },
    {
      Nombre: 'Cancer de Higado',
      'Piel Roja': 0,
      'Dolor al Orinar': 0,
      Tos: 0,
      Acidez: 0.8,
      Cansancio: 0.8,
      'Fiebre ': 0.4,
      'Cambio de Peso': 1,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0.2,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0.3,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 1,
      'Dolor en Abdomen': 0.8,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0, 0, 0.8, 0.8, 0.4, 1, 0, 0, 0.2, 0, 0.3, 0, 1, 0.8, 0, 0]
    },
    {
      Nombre: 'Cancer de Huesos',
      'Piel Roja': 0,
      'Dolor al Orinar': 0,
      Tos: 0,
      Acidez: 0,
      Cansancio: 1,
      'Fiebre ': 0.4,
      'Cambio de Peso': 1,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0,
      'Infección Recurrente': 0.1,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0,
      'Dolor en Huesos': 1,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0, 0, 0, 1, 0.4, 1, 0, 0, 0, 0.1, 0, 0, 0, 0, 1, 0]
    },
    {
      Nombre: 'Cancer de Mama',
      'Piel Roja': 0.5,
      'Dolor al Orinar': 0,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0.6,
      'Fiebre ': 0,
      'Cambio de Peso': 0.7,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 1,
      Array: [0.5, 0, 0, 0, 0.6, 0, 0.7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    },
    {
      Nombre: 'Cancer de Intestino delgado',
      'Piel Roja': 0.5,
      'Dolor al Orinar': 0,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0.9,
      'Fiebre ': 0,
      'Cambio de Peso': 1,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0.3,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 1,
      'Dolor en Abdomen': 0.7,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0.5, 0, 0, 0, 0.9, 0, 1, 0, 0, 0.3, 0, 0, 0, 1, 0.7, 0, 0]
    },
    {
      Nombre: 'Cancer de Pancreas',
      'Piel Roja': 0,
      'Dolor al Orinar': 0.8,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0.7,
      'Fiebre ': 0,
      'Cambio de Peso': 0.8,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0.7,
      Anemia: 0,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0.7,
      'Dolor en Abdomen': 0.9,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0.8, 0, 0, 0.7, 0, 0.8, 0, 0.7, 0, 0, 0, 0, 0.7, 0.9, 0, 0]
    },
    {
      Nombre: 'Cancer de Prostata',
      'Piel Roja': 0,
      'Dolor al Orinar': 1,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0,
      'Fiebre ': 0,
      'Cambio de Peso': 0.8,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0,
      'Dolor en Huesos': 0.8,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 1, 0, 0, 0, 0, 0.8, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0]
    },
    {
      Nombre: 'Cancer de Pulmón',
      'Piel Roja': 0,
      'Dolor al Orinar': 0,
      Tos: 1,
      Acidez: 0,
      Cansancio: 0.7,
      'Fiebre ': 0,
      'Cambio de Peso': 0.9,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0.6,
      'Dolor en Huesos': 0.7,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0, 1, 0, 0.7, 0, 0.9, 0, 0, 0, 0, 0, 0, 0, 0.6, 0.7, 0]
    },
    {
      Nombre: 'Cancer de Riñon',
      'Piel Roja': 0,
      'Dolor al Orinar': 0.8,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0.7,
      'Fiebre ': 0.7,
      'Cambio de Peso': 0.9,
      'Sangrados Nasales': 0,
      'Problemas de Coagulación': 0,
      Anemia: 0,
      'Infección Recurrente': 0,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0.3,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0, 0.8, 0, 0, 0.7, 0.7, 0.9, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0]
    },
    {
      Nombre: 'Leucemia',
      'Piel Roja': 0.6,
      'Dolor al Orinar': 0,
      Tos: 0,
      Acidez: 0,
      Cansancio: 0.4,
      'Fiebre ': 0.4,
      'Cambio de Peso': 0.5,
      'Sangrados Nasales': 0.6,
      'Problemas de Coagulación': 0.9,
      Anemia: 0.8,
      'Infección Recurrente': 0.7,
      'Dificultad para Tragar': 0,
      'Protuerancia en el cuello': 0,
      'Decoloración amarillenta en la piel': 0,
      'Dolor en Abdomen': 0,
      'Dolor en Huesos': 0,
      'Protuberancias desconocidas en la mama o axila': 0,
      Array: [0.6, 0, 0, 0, 0.4, 0.4, 0.5, 0.6, 0.9, 0.8, 0.7, 0, 0, 0, 0, 0, 0]
    }
  ]
}
