export default {

    
        data: [
            {
                "Nombre": "Cancer de Garganta",
                "Piel Roja": 0,
                "Dolor al Orinar": 0,
                "Tos": 1,
                "Acidez": 0,
                "Cansancio": .4,
                "Fiebre ": .1,
                "Cambio de Peso": .8,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": .2,
                "Infección Recurrente": .1,
                "Dificultad para Tragar": .8,
                "Protuerancia en el cuello": 1,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": 0,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,0,1,0,.4,.1,.8,0,0,.2,.1,.8,1,0,0,0,0]
            },
            {
                "Nombre": "Cancer de Higado",
                "Piel Roja": 0,
                "Dolor al Orinar": 0,
                "Tos": 0,
                "Acidez": .8,
                "Cansancio": .8,
                "Fiebre ": .4,
                "Cambio de Peso": 1,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": .2,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": .3,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 1,
                "Dolor en Abdomen": .8,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,0,0,.8,.8,.4,1,0,0,.2,0,.3,0,1,.8,0,0]
            },
            {
                "Nombre": "Cancer de Huesos",
                "Piel Roja": 0,
                "Dolor al Orinar": 0,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": 1,
                "Fiebre ": .4,
                "Cambio de Peso": 1,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": 0,
                "Infección Recurrente": .1,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": 0,
                "Dolor en Huesos": 1,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,0,0,0,1,.4,1,0,0,0,.1,0,0,0,0,1,0]
            },
            {
                "Nombre": "Cancer de Mama",
                "Piel Roja": .5,
                "Dolor al Orinar": 0,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": .6,
                "Fiebre ": 0,
                "Cambio de Peso": .7,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": 0,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": 0,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 1,
                "Array":[.5,0,0,0,.6,0,.7,0,0,0,0,0,0,0,0,0,1]
            },
            {
                "Nombre": "Cancer de Intestino delgado",
                "Piel Roja": .5,
                "Dolor al Orinar": 0,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": .9,
                "Fiebre ": 0,
                "Cambio de Peso": 1,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": .3,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 1,
                "Dolor en Abdomen": .7,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[.5,0,0,0,.9,0,1,0,0,.3,0,0,0,1,.7,0,0]
            },
            {
                "Nombre": "Cancer de Pancreas",
                "Piel Roja": 0,
                "Dolor al Orinar": .8,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": .7,
                "Fiebre ": 0,
                "Cambio de Peso": .8,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": .7,
                "Anemia": 0,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": .7,
                "Dolor en Abdomen": .9,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,.8,0,0,.7,0,.8,0,.7,0,0,0,0,.7,.9,0,0]
            },
            {
                "Nombre": "Cancer de Prostata",
                "Piel Roja": 0,
                "Dolor al Orinar": 1,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": 0,
                "Fiebre ": 0,
                "Cambio de Peso": .8,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": 0,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": 0,
                "Dolor en Huesos": .8,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,1,0,0,0,0,.8,0,0,0,0,0,0,0,0,.8,0]
            },
            {
                "Nombre": "Cancer de Pulmón",
                "Piel Roja": 0,
                "Dolor al Orinar": 0,
                "Tos": 1,
                "Acidez": 0,
                "Cansancio": .7,
                "Fiebre ": 0,
                "Cambio de Peso": .9,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": 0,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": .6,
                "Dolor en Huesos": .7,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,0,1,0,.7,0,.9,0,0,0,0,0,0,0,.6,.7,0]
            },
            {
                "Nombre": "Cancer de Riñon",
                "Piel Roja": 0,
                "Dolor al Orinar": .8,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": .7,
                "Fiebre ": .7,
                "Cambio de Peso": .9,
                "Sangrados Nasales": 0,
                "Problemas de Coagulación": 0,
                "Anemia": 0,
                "Infección Recurrente": 0,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": .3,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[0,.8,0,0,.7,.7,.9,0,0,0,0,0,0,0,.3,0,0]
            },
            {
                "Nombre": "Leucemia",
                "Piel Roja": .6,
                "Dolor al Orinar": 0,
                "Tos": 0,
                "Acidez": 0,
                "Cansancio": .4,
                "Fiebre ": .4,
                "Cambio de Peso": .5,
                "Sangrados Nasales": .6,
                "Problemas de Coagulación": .9,
                "Anemia": .8,
                "Infección Recurrente": .7,
                "Dificultad para Tragar": 0,
                "Protuerancia en el cuello": 0,
                "Decoloración amarillenta en la piel": 0,
                "Dolor en Abdomen": 0,
                "Dolor en Huesos": 0,
                "Protuberancias desconocidas en la mama o axila": 0,
                "Array":[.6,0,0,0,.4,.4,.5,.6,.9,.8,.7,0,0,0,0,0,0]
            },
            
        ]
    } 

